/* Return the maximum number of bytes that can be generated by
   applying FORMAT to an unsigned int value.  If the format is
   invalid, diagnose the problem and exit.  */
static size_t
max_out (char *format)
{
  bool percent = false;

  for (char *f = format; *f; f++)
    if (*f == '%' && *++f != '%')
      {
        if (percent)
          error (EXIT_FAILURE, 0,
                 _("too many %% conversion specifications in suffix"));
        percent = true;
        int flags;
        f += get_format_flags (f, &flags);
        while (ISDIGIT (*f))
          f++;
        if (*f == '.')
          while (ISDIGIT (*++f))
            continue;
        check_format_conv_type (f, flags);
      }

  if (! percent)
    error (EXIT_FAILURE, 0,
           _("missing %% conversion specification in suffix"));

  int maxlen = snprintf (NULL, 0, format, UINT_MAX);
  if (! (0 <= maxlen && maxlen <= SIZE_MAX))
    xalloc_die ();
  return maxlen;
}

